---
- name: Update the system
  hosts: all
  tasks:
    - name: Update and upgrade apt packages
      become: true
      # ansible package module
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400 # One day
