---
- name: Add Grafana repository key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
    validate_certs: no

- name: Add Grafana repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    validate_certs: no

- name: Install Grafana
  become: true
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: yes

- name: Enable Grafana service
  become: true
  ansible.builtin.service:
    name: grafana-server
    enabled: yes
    state: started

- name: Check if Grafana is running
  ansible.builtin.wait_for:
    port: 3000
    delay: 5
    timeout: 10
    state: started
    msg: Grafana is not running
