---
- name: Create prometheus folder
  become: true
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    owner: pi
    group: hadoop
    mode: "0755"

- name: Check if prometheus is already present
  ansible.builtin.stat:
    path: /tmp/prometheus-2.22.0.linux-armv7
  register: prometheus_check

- name: Extract prometheus
  become: true
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/../roles/prometheus/files/prometheus.tar.gz"
    dest: /tmp/
    owner: pi
    group: hadoop
    mode: "0755"
  when: not prometheus_check.stat.exists

- name: Rename prometheus binary
  ansible.builtin.copy:
    src: &binary_path /tmp/prometheus-2.22.0.linux-armv7/prometheus
    dest: /opt/prometheus/
    remote_src: true
    owner: pi
    group: hadoop
    mode: "0755"

- name: Remove prometheus binary
  become: true
  ansible.builtin.file:
    path: *binary_path
    state: absent

- name: Copy prometheus service file
  become: true
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../roles/prometheus/files/prometheus.service"
    dest: /etc/systemd/system/prometheus.service
    owner: pi
    group: hadoop
    mode: "0644"

- name: Copy prometheus configuration
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../roles/prometheus/files/prometheus.yml"
    dest: /opt/prometheus/prometheus.yml
    owner: pi
    group: hadoop
    mode: "0644"

- name: Start prometheus service
  become: true
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

- name: Check if prometheus is running
  ansible.builtin.wait_for:
    port: 9090
    delay: 5
    timeout: 60
    state: started
